apiVersion: apps/v1
kind: Deployment
namespace: three-tier-app
metadata:
  name: myflask-app
  labels:
    app: myflask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myflask-app
  template:
    metadata:
      labels:
        app: myflask-app
    spec:
      containers:
        - name: myflask-app
          image: salehktk005/myflask-app:latest
          env:
            - name: MYSQL_HOST
              value: mysql          # this is your mysql's service clusture IP, Make sure to change it with yours
            - name: MYSQL_PASSWORD
              value: "admin"
            - name: MYSQL_USER
              value: "admin"
            - name: MYSQL_DB
              value: "mydb"
          ports:
            - containerPort: 5000
          imagePullPolicy: Always
