apiVersion: v1
kind: Service
namespace: three-tier-app
metadata:
  name: myflask-app-svc
spec:
  selector:
    app: myflask-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
    
