apiVersion: v1
kind: Service
metadata:
  name: three-tier-flask-app-svc
spec:
  selector:
    app: three-tier-flask-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
    
