apiVersion: v1
kind: Service
metadata:
  name: myflask-app
  namespace: flask-sql-namespace
spec:
  selector:
    app: myflask-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP