apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: flask-sql-namespace
type: Opaque
data:
  mysql-root-password: YWRtaW4=
  mysql-password: YWRtaW4=
  mysql-user: YWRtaW4=
  mysql-database: bXlkYg==
